app = "flask-pgvcl-billpay"
primary_region = "bom"
kill_signal = "SIGINT"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 25

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "get"
    path = "/healthz"
    protocol = "http"

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
