name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1
        with:
          version: v0.2.117

      - name: Deploy app
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_NONINTERACTIVE: 1
        run: |
          flyctl status --app flask-pgvcl-billpay || echo "App not found, needs creation"
          flyctl deploy --remote-only --app flask-pgvcl-billpay
