name: Deploy to Fly.io

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install flyctl manually
        run: |
          curl -L https://fly.io/install.sh | sh
          echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Verify app exists and deploy
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: |
          export FLY_NONINTERACTIVE=1
          
          # Check if app exists
          if ! flyctl apps list | grep -q "flask-pgvcl-billpay"; then
            echo "Creating app flask-pgvcl-billpay..."
            flyctl apps create flask-pgvcl-billpay --org personal
          fi
          
          # Deploy directly without launch workflow
          flyctl deploy --remote-only --app flask-pgvcl-billpay --dockerfile Dockerfile
